using CodeCool.SeasonalProductDiscounter.Model.Offers;
using CodeCool.SeasonalProductDiscounter.Model.Products;
using CodeCool.SeasonalProductDiscounter.Model.Transactions;
using CodeCool.SeasonalProductDiscounter.Model.Users;
using CodeCool.SeasonalProductDiscounter.Service.Discounts;
using CodeCool.SeasonalProductDiscounter.Service.Logger;
using CodeCool.SeasonalProductDiscounter.Service.Products.Repository;
using CodeCool.SeasonalProductDiscounter.Service.Transactions.Repository;
using CodeCool.SeasonalProductDiscounter.Service.Users;

namespace CodeCool.SeasonalProductDiscounter.Service.Transactions.Simulator;

public class TransactionsSimulator
{
    private static readonly Random Random = new();

    private readonly ILogger _logger;
    private readonly IUserRepository _userRepository;
    private readonly IProductRepository _productRepository;
    private readonly IAuthenticationService _authenticationService;
    private readonly IDiscounterService _discounterService;
    private readonly ITransactionRepository _transactionRepository;

    public TransactionsSimulator(
        ILogger logger,
        IUserRepository userRepository,
        IProductRepository productRepository,
        IAuthenticationService authenticationService,
        IDiscounterService discounterService,
        ITransactionRepository transactionRepository)
    {
        _logger = logger;
        _userRepository = userRepository;
        _productRepository = productRepository;
        _authenticationService = authenticationService;
        _discounterService = discounterService;
        _transactionRepository = transactionRepository;
    }

    public void Run(TransactionsSimulatorSettings settings)
    {
        int successfulTransactions = 0;
        int rounds = 1;

        _logger.LogInfo("Starting simulation");
        while (successfulTransactions <= settings.TransactionsCount)
        {
            _logger.LogInfo(
                $"Simulation round #{rounds++}, successful transactions: {successfulTransactions}/{settings.TransactionsCount}");

            //Get a random user
            var user = GetRandomUser(settings.UsersCount);
            _logger.LogInfo($"User [{user.UserName}] looking to buy a product");

            //Auth user
            if (!AuthUser(user))
            {
                //If auth is not successful, register the user
                _logger.LogInfo($"The user {user.UserName} is not registered yet!");
                RegisterUser(user);
            }

            //Get user from the repo to have an ID (ID is auto-generated by the database)
            user = GetUserFromRepo(user.UserName);

            //User selects product
            var product = SelectProduct(user);

            //Out of products to sell - terminate cycle
            if (product == null)
            {
                break;
            }
            _logger.LogInfo($"The user chose a product from products table \n{product}.");
            _productRepository.SetProductuser_id(product, user);
            //Get offer
            var offer = GetOffer(product, settings.Date);
            _logger.LogInfo($"For this product he gets offer {offer}.");

            //Create transaction
            var transaction = CreateTransaction(settings.Date, user, product, offer.Price);
            _logger.LogInfo($"Now he performs {transaction}.");

            //Save transaction & set product_sold to TRUE
            if (SaveTransaction(transaction))
            {
                _logger.LogInfo("This new transaction has been added to database!");
                SetProductAsSold(product);
                _logger.LogInfo("Chosen product has been set as sold in database!");
                successfulTransactions++;
            }
        }
    }


    private User GetRandomUser(int usersCount)
    {
        return new User(0, $"user{Random.Next(0, usersCount)}", "pw");
    }

    private User GetUserFromRepo(string username)
    {
        return _userRepository.Get(username);
    }

    private bool AuthUser(User user)
    {
        return _authenticationService.Authenticate(user);
    }

    private bool RegisterUser(User user)
    {
        return _userRepository.Add(user);
    }

    private Product? SelectProduct(User user)
    {
        return GetRandomProduct();
    }

    private Product? GetRandomProduct()
    {
        var allProducts = _productRepository.AvailableProducts.ToList();

        if (!allProducts.Any())
        {
            _logger.LogInfo("The products table is now empty. The user can't choose a product.");
            return null;
        }
        return allProducts[Random.Next(0, allProducts.Count)];
    }

    private Offer GetOffer(Product product, DateTime date)
    {
        Offer offer = _discounterService.GetOffer(product, date);
        return offer;
    }

    private Transaction CreateTransaction(DateTime date, User user, Product product, double price)
    {
        Transaction newTrans = new Transaction(0, date, user, product, price);
        return newTrans;
    }

    private bool SaveTransaction(Transaction transaction)
    {
        return _transactionRepository.Add(transaction);
    }

    private bool SetProductAsSold(Product product)
    {
        return _productRepository.SetProductAsSold(product);
    }
}
